models:
  - name: jncraton/LaMini-Flan-T5-783M-ct2-int8
    backend: ctranslate2
  - name: marella/gpt-2-ggml
    backend: ctransformers

logos:
  - default: Ravens
    path: /logos/ravens.ico

  - custom_url: Orange Ravens
    path: https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2023.png
  
  - custom_file_path:
    path: