models:
  - name: jncraton/LaMini-Flan-T5-783M-ct2-int8
    backend: ctranslate2
  - name: marella/gpt-2-ggml
    backend: ctransformers

logo: https://s3.amazonaws.com/jnswire/jns-media/aa/9b/12538934/7.jpg


#logos:
#  - default: Ravens
#    path: /logos/ravens.ico