# Configuration file for the "Inferential" web app. Specifies models, their backends, and the logo used in the application.

models:
  - name: jncraton/LaMini-Flan-T5-248M-ct2-int8
    backend: ctranslate2
    max_prompt_length: 250
  - name: jncraton/LaMini-GPT-124M-ct2-int8
    backend: ctranslate2
    max_prompt_length: 250
  - name: marella/gpt-2-ggml
    backend: ctransformers
    max_prompt_length: 250

# When changing the logo, be sure to resize it to 30px by 30px for the best quality
logo: /static/logos/default.png
