models:
  - name: jncraton/LaMini-Flan-T5-783M-ct2-int8
    backend: ctranslate2
  - name: marella/gpt-2-ggml
    backend: ctransformers

# To change the favicon, make a copy of the file and change the name to favicon.ico
logo: /logos/ravens.ico


#https://pbs.twimg.com/profile_images/1656713838253817888/zgt-dQ9n_400x400.jpg https://pbs.twimg.com/profile_images/1656713838253817888/zgt-dQ9n_400x400.jpg
# /logos/ravens.ico 