models:
  - name: TheBloke/Llama-2-7B-Chat-GGUF
    backend: ctransformers
  - name: LaMini-Flan-T5-783M-ct2-int8
    backend: ctranslate2
  - name: TheBloke/Llama-2-7B-Chat-GGML
    backend: ctransformers
  - name: TheBloke/Nous-Capybara-7B-v1.9-GGUF
    backend: ctransformers
