# A list of models with name and backend information
models:
  - name: flan-alpaca-base
    backend: ctransformers

  - name: your-model-name
    backend: ctranslate

  - name: another-model
    backend: ctransformers
