models:
  - name: TheBloke/Llama-2-7B-Chat-GGUF
    backend: ctransformers
  - name: jncraton/LaMini-Flan-T5-783M-ct2-int8
    backend: ctranslate2
  - name: TheBloke/Llama-2-7B-Chat-GGML
    backend: ctransformers
  - name: TheBloke/Nous-Capybara-7B-v1.9-GGUF
    backend: ctransformers
  - name: TheBloke/TinyLlama-1.1B-1T-OpenOrca-GGUF
    backend: ctransformers
  - name: marella/gpt-2-ggml
    backend: ctransformers
