name: Lint

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches: '**'
  workflow_dispatch:

jobs:
  Prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: pip install black
      - run: make lint
