name: Prettier

on:
  push:
    branches: '**'
  pull_request:
    branches: 
  workflow_dispatch:

jobs:
  Prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm install -g prettier
      - run: npm run lint
